# Compare `GENCODE GTF V24` to `V29` using `protein-coding` genes and `chr1-22` with final table and printed stats about exon and splice junction comparisons

In [1]:
import polars as pl
_=pl.Config.set_tbl_cols(100000)
_=pl.Config.set_tbl_rows(10000)
_=pl.Config.set_tbl_width_chars(10000)
_=pl.Config.set_fmt_str_lengths(10000)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from pathlib import Path

In [2]:
# Define the path to GTF files
gtf_path = Path("../../../../../data/annotations/")

# List only gzipped GTF files in the directory
gtf_files = list(gtf_path.glob("*.gtf.gz"))

print(f"Found {len(gtf_files)} gzipped GTF files:")
for file in gtf_files:
    print(f"  - {file.name}")

# Load GTF files into a dictionary organized by version (v24 and v29)
gtf_data = {}
# chromosomes to keep 
chromosomes_to_keep = [f"chr{i}" for i in range(1, 23)]  # chr1 to chr22

for file in gtf_files:
    # Extract version from filename (assumes filename contains v24 or v29)
    if ".v24." in file.name:
        version_key = "v24"
    elif ".v29." in file.name:
        version_key = "v29"
    else:
        continue  # Skip files that don't match expected versions
    
    gtf_data[version_key] = pl.read_csv(
        file,
        separator="\t",
        comment_prefix="#",
        has_header=False,
        new_columns=["seqname", "source", "feature", "start", "end", "score", "strand", "frame", "attribute"]
    ).filter(
        (pl.col("feature") == "exon") &  # Filter to keep only exon records
        (pl.col("seqname").is_in(chromosomes_to_keep))  # Keep only specified chromosomess
    )
    print(f"\nLoaded {gtf_data[version_key].shape[0]:,} records from {file.name}")

print(f"\nGTF data dictionary keys: {list(gtf_data.keys())}")

Found 2 gzipped GTF files:
  - gencode.v29.primary_assembly.annotation_UCSC_names.gtf.gz
  - gencode.v24.annotation.gtf.gz

Loaded 1,218,596 records from gencode.v29.primary_assembly.annotation_UCSC_names.gtf.gz

Loaded 1,137,684 records from gencode.v24.annotation.gtf.gz

GTF data dictionary keys: ['v29', 'v24']

In [3]:
for key in gtf_data: 
    key
    gtf_data[key].shape
    gtf_data[key].head()

'v29'

(1218596, 9)

shape: (5, 9)
┌─────────┬────────┬─────────┬───────┬───────┬───────┬────────┬───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ seqname ┆ source ┆ feature ┆ start ┆ end   ┆ score ┆ strand ┆ frame ┆ attribute                                                                                                                                                                                                                                                                                                                                                                                                                                      │
│ ---     ┆ ---    ┆ ---     ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---   ┆ ---                                                                                                                                                                                                                                                                                                                                                                                                                                            │
│ str     ┆ str    ┆ str     ┆ i64   ┆ i64   ┆ str   ┆ str    ┆ str   ┆ str                                                                                                                                                                                                                                                                                                                                                                                                                                            │
╞═════════╪════════╪═════════╪═══════╪═══════╪═══════╪════════╪═══════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ chr1    ┆ HAVANA ┆ exon    ┆ 11869 ┆ 12227 ┆ .     ┆ +      ┆ .     ┆ gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 1; exon_id "ENSE00002234944.1"; level 2; transcript_support_level "1"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";                                                      │
│ chr1    ┆ HAVANA ┆ exon    ┆ 12613 ┆ 12721 ┆ .     ┆ +      ┆ .     ┆ gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 2; exon_id "ENSE00003582793.1"; level 2; transcript_support_level "1"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";                                                      │
│ chr1    ┆ HAVANA ┆ exon    ┆ 13221 ┆ 14409 ┆ .     ┆ +      ┆ .     ┆ gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_name "DDX11L1-202"; exon_number 3; exon_id "ENSE00002312635.1"; level 2; transcript_support_level "1"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";                                                      │
│ chr1    ┆ HAVANA ┆ exon    ┆ 12010 ┆ 12057 ┆ .     ┆ +      ┆ .     ┆ gene_id "ENSG00000223972.5"; transcript_id "ENST00000450305.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-201"; exon_number 1; exon_id "ENSE00001948541.1"; level 2; transcript_support_level "NA"; ont "PGO:0000005"; ont "PGO:0000019"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000002844.2"; │
│ chr1    ┆ HAVANA ┆ exon    ┆ 12179 ┆ 12227 ┆ .     ┆ +      ┆ .     ┆ gene_id "ENSG00000223972.5"; transcript_id "ENST00000450305.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_name "DDX11L1"; transcript_type "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-201"; exon_number 2; exon_id "ENSE00001671638.2"; level 2; transcript_support_level "NA"; ont "PGO:0000005"; ont "PGO:0000019"; tag "basic"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000002844.2"; │
└─────────┴────────┴─────────┴───────┴───────┴───────┴────────┴───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

'v24'

(1137684, 9)

shape: (5, 9)
┌─────────┬────────┬─────────┬───────┬───────┬───────┬────────┬───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ seqname ┆ source ┆ feature ┆ start ┆ end   ┆ score ┆ strand ┆ frame ┆ attribute                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      │
│ ---     ┆ ---    ┆ ---     ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---   ┆ ---                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            │
│ str     ┆ str    ┆ str     ┆ i64   ┆ i64   ┆ str   ┆ str    ┆ str   ┆ str                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            │
╞═════════╪════════╪═════════╪═══════╪═══════╪═══════╪════════╪═══════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ chr1    ┆ HAVANA ┆ exon    ┆ 11869 ┆ 12227 ┆ .     ┆ +      ┆ .     ┆ gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_status "KNOWN"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_status "KNOWN"; transcript_name "DDX11L1-002"; exon_number 1; exon_id "ENSE00002234944.1"; level 2; tag "basic"; transcript_support_level "1"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";                                                      │
│ chr1    ┆ HAVANA ┆ exon    ┆ 12613 ┆ 12721 ┆ .     ┆ +      ┆ .     ┆ gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_status "KNOWN"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_status "KNOWN"; transcript_name "DDX11L1-002"; exon_number 2; exon_id "ENSE00003582793.1"; level 2; tag "basic"; transcript_support_level "1"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";                                                      │
│ chr1    ┆ HAVANA ┆ exon    ┆ 13221 ┆ 14409 ┆ .     ┆ +      ┆ .     ┆ gene_id "ENSG00000223972.5"; transcript_id "ENST00000456328.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_status "KNOWN"; gene_name "DDX11L1"; transcript_type "processed_transcript"; transcript_status "KNOWN"; transcript_name "DDX11L1-002"; exon_number 3; exon_id "ENSE00002312635.1"; level 2; tag "basic"; transcript_support_level "1"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000362751.1";                                                      │
│ chr1    ┆ HAVANA ┆ exon    ┆ 12010 ┆ 12057 ┆ .     ┆ +      ┆ .     ┆ gene_id "ENSG00000223972.5"; transcript_id "ENST00000450305.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_status "KNOWN"; gene_name "DDX11L1"; transcript_type "transcribed_unprocessed_pseudogene"; transcript_status "KNOWN"; transcript_name "DDX11L1-001"; exon_number 1; exon_id "ENSE00001948541.1"; level 2; ont "PGO:0000005"; ont "PGO:0000019"; tag "basic"; transcript_support_level "NA"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000002844.2"; │
│ chr1    ┆ HAVANA ┆ exon    ┆ 12179 ┆ 12227 ┆ .     ┆ +      ┆ .     ┆ gene_id "ENSG00000223972.5"; transcript_id "ENST00000450305.2"; gene_type "transcribed_unprocessed_pseudogene"; gene_status "KNOWN"; gene_name "DDX11L1"; transcript_type "transcribed_unprocessed_pseudogene"; transcript_status "KNOWN"; transcript_name "DDX11L1-001"; exon_number 2; exon_id "ENSE00001671638.2"; level 2; ont "PGO:0000005"; ont "PGO:0000019"; tag "basic"; transcript_support_level "NA"; havana_gene "OTTHUMG00000000961.2"; havana_transcript "OTTHUMT00000002844.2"; │
└─────────┴────────┴─────────┴───────┴───────┴───────┴────────┴───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [4]:
# Create exon and splice junction databases for each GTF version
exon_db = {}
splice_junction_db = {}

for version, gtf_df in gtf_data.items():
    # Create exon database: combine seqname, start, end, strand with "_"
    exon_db[version] = set(
        gtf_df.select([
            pl.concat_str(
                [pl.col("seqname"), pl.col("start"), pl.col("end"), pl.col("strand")],
                separator="_"
            ).alias("exon_id")
        ]).to_series().to_list()
    )
    
    # Create splice junction database: combine seqname with start and end positions, plus strand
    start_junctions = set(
        gtf_df.select(pl.concat_str(
            [pl.col("seqname"), pl.col("start"), pl.col("strand")],
            separator="_"
        ).alias("junction_id")).to_series().to_list()
    )
    
    end_junctions = set(
        gtf_df.select(pl.concat_str(
            [pl.col("seqname"), pl.col("end"), pl.col("strand")],
            separator="_"
        ).alias("junction_id")).to_series().to_list()
    )
    
    splice_junction_db[version] = start_junctions.union(end_junctions)
    
    print(f"\n{version}:")
    print(f"  Exons: {len(exon_db[version])}")
    print(f"  Splice junctions: {len(splice_junction_db[version])}")

v29:
  Exons: 569860
  Splice junctions: 908208

v24:
  Exons: 550670
  Splice junctions: 883093

In [5]:
# Calculate unique exons and splice junctions for each version
exons_v24_only = exon_db['v24'] - exon_db['v29']
exons_v29_only = exon_db['v29'] - exon_db['v24']

junctions_v24_only = splice_junction_db['v24'] - splice_junction_db['v29']
junctions_v29_only = splice_junction_db['v29'] - splice_junction_db['v24']

print("Unique to v24:")
print(f"  Exons: {len(exons_v24_only)}")
print(f"  Splice junctions: {len(junctions_v24_only)}")

print("\nUnique to v29:")
print(f"  Exons: {len(exons_v29_only)}")
print(f"  Splice junctions: {len(junctions_v29_only)}")

Unique to v24:
  Exons: 9305
  Splice junctions: 13122

Unique to v29:
  Exons: 28495
  Splice junctions: 38237

In [6]:
# Create comparison table using Polars

# Calculate shared exons and junctions
shared_exons = exon_db['v24'] & exon_db['v29']
shared_junctions = splice_junction_db['v24'] & splice_junction_db['v29']

# Create the comparison table
comparison_data = {
    'Annotation': ['v24', 'v29'],

    'Total Protein-Coding Exons': [len(exon_db['v24']), len(exon_db['v29'])],
    'Total Protein-Coding Splice Junctions': [len(splice_junction_db['v24']), len(splice_junction_db['v29'])],

    '# Unique Exons vs Other Version': [len(exons_v24_only), len(exons_v29_only)],
    '# Shared Exons': [len(shared_exons), len(shared_exons)],
    '% This Annotation\'s Exons Shared': [(len(shared_exons) / len(exon_db['v24'])) * 100, (len(shared_exons) / len(exon_db['v29'])) * 100],
    '# Unique Splice Junctions vs Other Version': [len(junctions_v24_only), len(junctions_v29_only)],
    '# Shared Splice Junctions': [len(shared_junctions), len(shared_junctions)],
    '% This Annotation\'s Splice Junctions Shared': [(len(shared_junctions) / len(splice_junction_db['v24'])) * 100, (len(shared_junctions) / len(splice_junction_db['v29'])) * 100]
}

comparison_df = pl.DataFrame(comparison_data)
comparison_df 

# Calculate percentages
union_exons = exon_db['v24'] | exon_db['v29']
union_junctions = splice_junction_db['v24'] | splice_junction_db['v29']

exon_shared_percentage = (len(shared_exons) / len(union_exons)) * 100
junction_shared_percentage = (len(shared_junctions) / len(union_junctions)) * 100

print(f"\nPercentage of exons shared (where divisor is union of exons across both versions): {exon_shared_percentage:.2f}%")
print(f"Percentage of splice junctions shared (where divisor is union of junctions across both versions): {junction_shared_percentage:.2f}%")

shape: (2, 9)
┌────────────┬────────────────────────────┬───────────────────────────────────────┬─────────────────────────────────┬────────────────┬──────────────────────────────────┬────────────────────────────────────────────┬───────────────────────────┬─────────────────────────────────────────────┐
│ Annotation ┆ Total Protein-Coding Exons ┆ Total Protein-Coding Splice Junctions ┆ # Unique Exons vs Other Version ┆ # Shared Exons ┆ % This Annotation's Exons Shared ┆ # Unique Splice Junctions vs Other Version ┆ # Shared Splice Junctions ┆ % This Annotation's Splice Junctions Shared │
│ ---        ┆ ---                        ┆ ---                                   ┆ ---                             ┆ ---            ┆ ---                              ┆ ---                                        ┆ ---                       ┆ ---                                         │
│ str        ┆ i64                        ┆ i64                                   ┆ i64                             ┆ i64            ┆ f64                              ┆ i64                                        ┆ i64                       ┆ f64                                         │
╞════════════╪════════════════════════════╪═══════════════════════════════════════╪═════════════════════════════════╪════════════════╪══════════════════════════════════╪════════════════════════════════════════════╪═══════════════════════════╪═════════════════════════════════════════════╡
│ v24        ┆ 550670                     ┆ 883093                                ┆ 9305                            ┆ 541365         ┆ 98.31024                         ┆ 13122                                      ┆ 869971                    ┆ 98.514086                                   │
│ v29        ┆ 569860                     ┆ 908208                                ┆ 28495                           ┆ 541365         ┆ 94.999649                        ┆ 38237                                      ┆ 869971                    ┆ 95.789841                                   │
└────────────┴────────────────────────────┴───────────────────────────────────────┴─────────────────────────────────┴────────────────┴──────────────────────────────────┴────────────────────────────────────────────┴───────────────────────────┴─────────────────────────────────────────────┘

Percentage of exons shared (where divisor is union of exons across both versions): 93.47%
Percentage of splice junctions shared (where divisor is union of junctions across both versions): 94.43%