# Data Validations

## Purpose: 
* Check `Unique Binding Pattern` (`UBP`) table
* Make sure no variance in `expected value` from `SHAP`
* Make sure that `SHAP additivity` principle holds up for randomly sampled rows
* Check that no UBP ID is duplicated across sharded `Feather` files for that cell line

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_colwidth', 1000)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import polars as pl 

_=pl.Config.set_tbl_cols(1000)
_=pl.Config.set_tbl_rows(1000)
_=pl.Config.set_tbl_width_chars(10000)
_=pl.Config.set_fmt_str_lengths(10000)

import numpy as np
import sys, yaml, glob

with open("1_metadata_variables.yaml", 'r') as f:
    metadata_variables = yaml.safe_load(f)

## View `Unique Binding Pattern (UBP)` ID Table

In [2]:
for cell_line in metadata_variables['CELL_LINES']: 

    pl.scan_csv(
        f"../outputs/ubp_ID_tables/{cell_line}_unique_binding_pattern_ID_reference_table.tsv.gz", 
        separator="\t"
    ).head(20).collect()

shape: (20, 631)
┌───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐

shape: (20, 835)
┌───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬───────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐

## No Variance in Expected Value

In [3]:
for cell_line in metadata_variables["CELL_LINES"]: 
    files = glob.glob(f"../outputs/expected_values/{cell_line}_*.txt")

    f"Number of files for {cell_line}: {len(files)}"

    expected_values = []

    for file in files: 
        with open(file, 'r') as in_file: 
            
            expected_values.append(
                float(in_file.readline().strip())
            )

    pd.Series(expected_values).describe()

'Number of files for HepG2: 116'

count    116.000000
mean       1.592609
std        0.000000
min        1.592609
25%        1.592609
50%        1.592609
75%        1.592609
max        1.592609
dtype: float64

'Number of files for K562: 149'

count    149.000000
mean       1.622543
std        0.000000
min        1.622543
25%        1.622543
50%        1.622543
75%        1.622543
max        1.622543
dtype: float64

## Check Additivity for Randomly Sampled Rows

In [4]:
import random, gzip, pickle

In [7]:
seed = random.randint(1, 9000)
f"Seed: {seed}" 
random.seed(seed)

for cell_line in metadata_variables["CELL_LINES"]: 
    files = glob.glob(f"../outputs/flattened_interaction_value_tables/{cell_line}_*")
    files = random.sample(files, 2)

    files

    ubp_id_table_path = f"{metadata_variables['UBP_ID_TABLE_DIR']}/{cell_line}_unique_binding_pattern_ID_reference_table.tsv.gz"
    ubp_id_table = pl.read_csv(
        ubp_id_table_path,
        separator="\t", 
    )
    
    model_hash= metadata_variables["XGBOOST_BEST_MODEL_HASHES"][cell_line]
    model_path = f'{metadata_variables["MODEL_DIR"]}/{model_hash}.pkl.gz'

    # Load the model
    with gzip.open(model_path, 'rb') as f:
        model = pickle.load(f)

    with open(f"../outputs/expected_values/{cell_line}_1-1000_expected_value.txt", 'r') as in_file: 
        expected_value = float(in_file.readline().strip())

    f"Expected value: {expected_value}"
        
    for file_path in files:
        # Read the IPC scan file
        lf = pl.scan_ipc(file_path)
        shap_columns = [col for col in lf.collect_schema().names() if col.endswith('-shap')]
        
        shap_sum = lf.select(shap_columns).with_columns(
            pl.sum_horizontal(shap_columns).alias("shap_sum")
        ).select("shap_sum").collect()["shap_sum"].to_numpy()
        assert shap_sum.ndim == 1, "shap_sum is not a 1D array"

        splitter = file_path.split("/")[-1].split("-")
        start_id = int(splitter[0].split("_")[-1])
        end_id = int(splitter[1].split("_")[0])

        start_id
        end_id
        
        X = ubp_id_table.filter(
            (pl.col("Unique Binding Pattern ID #") >= start_id) & 
            (pl.col("Unique Binding Pattern ID #") <= end_id)      
        ).select(
            [col for col in ubp_id_table.columns if col.endswith("_binding")]
        ).to_pandas()
            
        # Predict with output_margin=True
        preds = model.predict(X, output_margin=True)
        
        # Calculate distribution: horizontal sum of SHAP columns + expected_value - prediction
        distribution = shap_sum + expected_value - preds
        distribution = pd.Series(distribution,)

        distribution.describe()
        distribution.head()

'Seed: 2695'

['../outputs/flattened_interaction_value_tables/HepG2_UBP_IDs_6001-7000_shap_interactions.feather',
 '../outputs/flattened_interaction_value_tables/HepG2_UBP_IDs_36001-37000_shap_interactions.feather']

'Expected value: 1.5926086902618408'

6001

7000

count    1.000000e+03
mean    -2.731371e-08
std      1.538024e-06
min     -5.722046e-06
25%     -9.536743e-07
50%      0.000000e+00
75%      8.642673e-07
max      5.722046e-06
dtype: float64

0    5.960464e-07
1    9.536743e-07
2    0.000000e+00
3    9.536743e-07
4    2.384186e-06
dtype: float32

36001

37000

count    1.000000e+03
mean     1.479220e-08
std      1.266850e-06
min     -5.722046e-06
25%     -7.152557e-07
50%      0.000000e+00
75%      4.768372e-07
max      4.768372e-06
dtype: float64

0    3.576279e-07
1    9.536743e-07
2   -1.907349e-06
3    2.384186e-07
4    4.768372e-07
dtype: float32

['../outputs/flattened_interaction_value_tables/K562_UBP_IDs_98001-99000_shap_interactions.feather',
 '../outputs/flattened_interaction_value_tables/K562_UBP_IDs_21001-22000_shap_interactions.feather']

'Expected value: 1.6225428581237793'

98001

99000

count    1.000000e+03
mean    -4.054289e-07
std      7.325997e-06
min     -3.433228e-05
25%     -1.236796e-06
50%      1.668930e-06
75%      4.291534e-06
max      1.573563e-05
dtype: float64

0    0.000005
1    0.000002
2    0.000001
3    0.000001
4    0.000001
dtype: float32

21001

22000

count    1.000000e+03
mean    -2.342432e-06
std      7.444457e-06
min     -2.479553e-05
25%     -8.583069e-06
50%      4.768372e-07
75%      3.576279e-06
max      1.144409e-05
dtype: float64

0   -6.675720e-06
1   -6.198883e-06
2    7.152557e-07
3    7.629395e-06
4    6.198883e-06
dtype: float32

## No Duplicated UBP IDs Per Cell Line

In [8]:
for cell_line in metadata_variables["CELL_LINES"]: 
    interaction_val_path = f"{metadata_variables["SHAP_INTERACTION_VALUES_DIR"]}/{cell_line}_*.feather"

    interaction_ubp_ids = pl.scan_ipc(
        interaction_val_path
    ).select(
        "Unique Binding Pattern ID #"
    ).collect()

    interaction_ubp_ids.head(10)

    ubp_id_table_path = f"{metadata_variables['UBP_ID_TABLE_DIR']}/{cell_line}_unique_binding_pattern_ID_reference_table.tsv.gz"
    reference_ubp_ids = pl.scan_csv(
        ubp_id_table_path,
        separator="\t", 
    ).select(
        "Unique Binding Pattern ID #"
    ).collect()

    reference_ubp_ids.head(10)

    assert interaction_ubp_ids["Unique Binding Pattern ID #"].is_unique().all(), "Duplicate values found in interaction ubp ids"
    assert reference_ubp_ids["Unique Binding Pattern ID #"].is_unique().all(), "Duplicate values found in reference ubp ids"

    interaction_ubp_ids_list = sorted(interaction_ubp_ids["Unique Binding Pattern ID #"].to_numpy().tolist())
    reference_ubp_ids_list = sorted(reference_ubp_ids["Unique Binding Pattern ID #"].to_numpy().tolist())

    assert interaction_ubp_ids_list == reference_ubp_ids_list, "Interaction ubp ids and reference ubp ids do not match"

shape: (10, 1)
┌─────────────────────────────┐
│ Unique Binding Pattern ID # │
│ ---                         │
│ u32                         │
╞═════════════════════════════╡
│ 1                           │
│ 2                           │
│ 3                           │
│ 4                           │
│ 5                           │
│ 6                           │
│ 7                           │
│ 8                           │
│ 9                           │
│ 10                          │
└─────────────────────────────┘

shape: (10, 1)
┌─────────────────────────────┐
│ Unique Binding Pattern ID # │
│ ---                         │
│ i64                         │
╞═════════════════════════════╡
│ 1                           │
│ 2                           │
│ 3                           │
│ 4                           │
│ 5                           │
│ 6                           │
│ 7                           │
│ 8                           │
│ 9                           │
│ 10                          │
└─────────────────────────────┘

shape: (10, 1)
┌─────────────────────────────┐
│ Unique Binding Pattern ID # │
│ ---                         │
│ u32                         │
╞═════════════════════════════╡
│ 1                           │
│ 2                           │
│ 3                           │
│ 4                           │
│ 5                           │
│ 6                           │
│ 7                           │
│ 8                           │
│ 9                           │
│ 10                          │
└─────────────────────────────┘

shape: (10, 1)
┌─────────────────────────────┐
│ Unique Binding Pattern ID # │
│ ---                         │
│ i64                         │
╞═════════════════════════════╡
│ 1                           │
│ 2                           │
│ 3                           │
│ 4                           │
│ 5                           │
│ 6                           │
│ 7                           │
│ 8                           │
│ 9                           │
│ 10                          │
└─────────────────────────────┘